### PR TITLE
Speedup improvements

### PR DESCRIPTION
**Pull request by domenkozar**
This superseeds "speedup" branch. Lazily figure out what distributions required a dependency.

### CODE REVIEW

**Comment by cjw296** [comment]
I tried to run the tests from your branch:

buzzkill:buildout-versions chris$ python2.6 bootstrap.py
Downloading http://pypi.python.org/packages/2.6/s/setuptools/setuptools-0.6c11-py2.6.egg
buzzkill:buildout-versions chris$ bin/buildout
Develop: '/Users/chris/LocalGIT/buildout-versions/.'
Uninstalling test.
Installing test.
Getting distribution for 'testfixtures'.
Got testfixtures 2.3.5.
Generated script '/Users/chris/LocalGIT/buildout-versions/bin/test'.
Updating py.
Updating docs.
Generated script '/Users/chris/LocalGIT/buildout-versions/bin/sphinx-apidoc'.
Generated script '/Users/chris/LocalGIT/buildout-versions/bin/sphinx-build'.
Generated script '/Users/chris/LocalGIT/buildout-versions/bin/sphinx-quickstart'.
Generated script '/Users/chris/LocalGIT/buildout-versions/bin/sphinx-autogen'.
Generated script '/Users/chris/LocalGIT/buildout-versions/bin/rst2'.
Generated script '/Users/chris/LocalGIT/buildout-versions/bin/pkginfo'.
Generated interpreter '/Users/chris/LocalGIT/buildout-versions/bin/docpy'.
buzzkill:buildout-versions chris$ bin/test
Running zope.testrunner.layer.UnitTests tests:
  Set up zope.testrunner.layer.UnitTests in 0.000 seconds.

Error in test /Users/chris/LocalGIT/buildout-versions/docs/use.txt
Traceback (most recent call last):
  File "/usr/local/lib/python2.6/unittest.py", line 279, in run
    testMethod()
  File "/Users/chris/buildout-eggs/manuel-1.6.0-py2.6.egg/manuel/testing.py", line 38, in runTest
    self.regions.evaluate_with(self.manuel, self.globs)
  File "/Users/chris/buildout-eggs/manuel-1.6.0-py2.6.egg/manuel/**init**.py", line 156, in evaluate_with
    evaluater(region, self, globs)
  File "/Users/chris/buildout-eggs/manuel-1.6.0-py2.6.egg/manuel/codeblock.py", line 30, in execute_code_block
    exec(region.parsed.code, globs)
  File "/Users/chris/LocalGIT/buildout-versions/docs/use.txt:27", line 3, in <module>
  File "/Users/chris/LocalGIT/buildout-versions/src/buildout_versions/tests/test_docs.py", line 164, in run_buildout
    compare(fix_expected(expected),fix_actual(actual))
  File "/Users/chris/LocalGIT/buildout-versions/src/buildout_versions/tests/test_docs.py", line 26, in **call**
    line = f(line)
  File "/Users/chris/LocalGIT/buildout-versions/src/buildout_versions/tests/test_docs.py", line 104, in normalise_versions
    version = require(package)[0].version
  File "/Users/chris/buildout-eggs/setuptools-0.6c12dev_r88846-py2.6.egg/pkg_resources.py", line 666, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Users/chris/buildout-eggs/setuptools-0.6c12dev_r88846-py2.6.egg/pkg_resources.py", line 565, in resolve
    raise DistributionNotFound(req)  # XXX put more info here
DistributionNotFound: distribute

**Comment by domenkozar** [comment]
Those doc tests really suck, since they are environment dependant. I'll try to fix this setuptools/distribute mess.

**Comment by cjw296** [comment]
Personally, I'm not in favour of distribute. How did you end up with distribute in there? bootstrap.py -d?

**Comment by domenkozar** [comment]
I have no idea, it was in test errors. Seems like global-something effect.

**Comment by cjw296** [comment]
I'm sorry, couldn't extract any meaning from your last comment...

**Comment by domenkozar** [comment]
I pushed another commit, can you pull and try again?

**Comment by domenkozar** [comment]
Any further input? This fixes test failures you have described.

**Comment by cjw296** [comment]
Domen, I can appreciate your desire to get this fixed, but it's a subtle and complicated area that can't be rushed...

**Comment by domenkozar** [comment]
Agreed, let's sort out the issues! Although it seems the patch doesn't have regressions in tests.

**Comment by domenkozar** [comment]
To me it seems this is a side effect of environment for functional tests that buildout-versions is running. Could you take a look? I hit a dead end.

**Comment by domenkozar** [comment]
Nevermind, I'll use dumppickedversions with a few fixes.

**Pull request closed without merging**
